tabs:
  - name: "Basic"
    label: "基本设置"
    items:
      - name: "telegram"
        label: "telegram"
        type: "input"
      - name: "github"
        label: "github"
        type: "input"
      - name: "mail"
        label: "邮箱"
        type: "input"
      - name: "payQRCode"
        label: "收款二维码"
        type: "image"
      - name: "hobbies"
        label: "footer 打字机后缀"
        type: "list"
